---
title: "Reporte de Captura por unidad de esfuerzo (CPUE)"
author: "IMARPE - DGIRP"
header-includes:
  - \usepackage{fancyhdr}
  - \fancyfoot[LE,RO]{DGIRP}
  - \usepackage[spanish]{babel}
  - \usepackage[utf8]{inputenc}
fontsize: 10pt
geometry: margin=1cm
output: pdf_document
---

\pagenumbering{gobble}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Cpue por mes y tipo de flota
```{r, echo=FALSE, cache=TRUE, message=FALSE}
fleeTable = x$fleeTable
pander::pander(fleeTable, align = "c", keep.line.breaks = TRUE)
```

# Cpue diario
```{r, cache=TRUE, echo=FALSE, message=FALSE, fig.height=4.5, fig.width=8}
plot(x, language = "spanish", ploType = "plotDaily", col = "black", main = "", daysToPlot = daysToPlot)
```

\pagebreak

# Cpue mensual
\vspace{1.5cm}
```{r, echo=FALSE, cache=TRUE, message=FALSE}
monthTable = .getMonth.cpue(object=x, language="spanish")
pander::pander(monthTable, align = "c", keep.line.breaks = TRUE)
```
\vspace{3cm}
```{r, cache=TRUE, echo=FALSE, message=FALSE, fig.height= 4.5, fig.width=8}
plot(x, language = "spanish", ploType = "plotMonthly", col = "gray", main = "")
```

\pagebreak

# Cpue anual
\vspace{1.5cm}
```{r, echo=FALSE, cache=TRUE, message=FALSE}
yearTable = .getYear.cpue(object=x)
pander::pander(yearTable, align = "c", keep.line.breaks = TRUE)
```
\vspace{3cm}
```{r, cache=TRUE, echo=FALSE, message=FALSE, fig.height=5.5, fig.width=6.5}
plot(x, language = "spanish", ploType = "plotYearly", col = "gray", main = "")
```

\pagebreak

# Cpue por puerto
```{r, echo=FALSE, cache=TRUE, message=FALSE}
portTable = x$dataPort
pander::pander(portTable, align = "c", keep.line.breaks = TRUE)
```

# Cpue diario y acumulado en la region Norte-Centro
```{r, cache=TRUE, echo=FALSE, message=FALSE, fig.height=6, fig.width=9, dpi=72}
plot(x, language = "spanish", ploType = "plotNC", daysToPlot = daysToPlot, textAxis2 = textAxis2, textAxis4 = textAxis4)
```

\pagebreak

# Cpue diario y acumulado en la region Sur
```{r, cache=TRUE, echo=FALSE, message=FALSE, fig.height=6, fig.width=9, dpi=72}
plot(x, language = "spanish", ploType = "plotS", daysToPlot = daysToPlot, textAxis2 = textAxis2, textAxis4 = textAxis4)
```
