---
title: "Reporte de Esfuerzo"
author: "IMARPE - DGIRP"
header-includes:
  - \usepackage{fancyhdr}
  - \fancyfoot[LE,RO]{DGIRP}
  - \usepackage[spanish]{babel}
fontsize: 10pt
geometry: margin=1cm
keep_tex: yes
output: pdf_document
---

\pagenumbering{gobble}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Esfuerzo total
```{r, echo=FALSE, message=FALSE}
monthTable = .getMonth.fishery(object=x, language="spanish")
rowNamesTable = rownames(monthTable)
colNamesTable = colnames(monthTable)

monthTable = rbind(monthTable, apply(monthTable, 2, sum, na.rm = TRUE))
rownames(monthTable) = c(rowNamesTable, "Total")
monthTable = cbind(monthTable, apply(monthTable, 1, sum, na.rm = TRUE))
colnames(monthTable) = c(colNamesTable, "Total")

monthTable = round(x = monthTable, digits = 2)

pander::pander(monthTable, align = "c", keep.line.breaks = TRUE)
```

# Esfuerzo por tipo de flota
```{r, echo=FALSE, message=FALSE}
fleeTable = x$fleeTable
rowNamesTable = rownames(fleeTable)
colNamesTable = colnames(fleeTable)

fleeTable = rbind(fleeTable, apply(fleeTable, 2, sum, na.rm = TRUE))
rownames(fleeTable) = c(rowNamesTable, "Total")

fleeTable = cbind(fleeTable, apply(fleeTable, 1, sum, na.rm = TRUE))
colnames(fleeTable) = c(colNamesTable, "Total")

fleeTable = round(x = fleeTable, digits = 2)

pander::pander(fleeTable, align = "c", keep.line.breaks = TRUE)
```
\pagebreak

# Esfuerzo diario, mensual y anual

```{r, echo=FALSE, message=FALSE, fig.height=4, fig.width=8}
plot(x, language = "spanish", ploType = "plotDaily", col = "black", main = "", daysToPlot = daysToPlot)
```

```{r, echo=FALSE, message=FALSE, fig.height= 3.5, fig.width=7.5}
plot(x, language = "spanish", ploType = "plotMonthly", col = "gray", main = "")
```

```{r, echo=FALSE, message=FALSE, fig.height=2, fig.width=3}
plot(x, language = "spanish", ploType = "plotYearly", col = "gray", main = "")
```

\pagebreak

# Esfuerzo por puerto
```{r, echo=FALSE, message=FALSE}
portTable = x$data
yearsTable = sort(unique(portTable$year), decreasing = FALSE)

portTable = melt(portTable, id.vars= names(portTable[ , c(1:3)]))
portTable = tapply(portTable$value, list(portTable[, 1], portTable[, 4]), sum)

portInfo = getPort(colnames(portTable))
colnames(portTable) = portInfo$data$name

if(dim(portTable)[2] == 1){
  rowNamesTable = rownames(portTable)
  portTable = rbind(portTable, apply(portTable, 2, sum, na.rm = TRUE))
  rownames(portTable) = c(rowNamesTable, "Total")
  
} else {
  portTable = portTable[, order(portInfo$data$lat, decreasing = TRUE)]
  portTable = as.data.frame(portTable)
  
  if(dim(portTable)[2] == 1){
    colnames(portTable) = yearsTable
    rowNamesTable = rownames(portTable)
    
    portTable = rbind(portTable, apply(portTable, 2, sum, na.rm = TRUE))
    rownames(portTable) = c(rowNamesTable, "Total")
    
  } else {
    portTable = t(portTable)
    
    colNamesTable = yearsTable
    rowNamesTable = rownames(portTable)
    
    portTable = rbind(portTable, apply(portTable, 2, sum, na.rm = TRUE))
    rownames(portTable) = c(rowNamesTable, "Total")
    portTable = cbind(portTable, apply(portTable, 1, sum, na.rm = TRUE))
    colnames(portTable) = c(colNamesTable, "Total")
    
  }
}
portTable = round(x = portTable, digits = 2)

pander::pander(portTable, align = "c", keep.line.breaks = TRUE)
```

# Esfuerzo acumulado en el dominio peruano
```{r, echo=FALSE, message=FALSE, fig.height=6, fig.width=9, dpi=72}
plot(x, language = "spanish", ploType = "plotPERU", daysToPlot = daysToPlot, textAxis2 = textAxis2, textAxis4 = textAxis4)
```

# Esfuerzo acumulado en la región Norte-Centro
```{r, echo=FALSE, message=FALSE, fig.height=5.5, fig.width=9.5, dpi=72}
plot(x, language = "spanish", ploType = "plotNC", daysToPlot = daysToPlot, textAxis2 = textAxis2, textAxis4 = textAxis4)
```

# Esfuerzo acumulado en la región Sur
```{r, echo=FALSE, message=FALSE, fig.height=5.5, fig.width=9.5, dpi=72}
plot(x, language = "spanish", ploType = "plotS", daysToPlot = daysToPlot, textAxis2 = textAxis2, textAxis4 = textAxis4)
```
