---
title: "Reporte de Desembarque y Esfuerzo"
author: "IMARPE - DGIRP"
header-includes:
  - \usepackage{fancyhdr}
  - \fancyfoot[LE,RO]{DGIRP}
  - \usepackage[spanish]{babel}
fontsize: 10pt
geometry: margin=0.5cm
keep_tex: yes
output: pdf_document
---

\pagenumbering{gobble}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Desembarque y esfuerzo por tipo de flota
```{r, echo=FALSE, message=FALSE}
fleeTableLanding = round(x = x$landing$fleeTable, digits = 2)
fleeTableEffort  = round(x = x$effort$fleeTable, digits = 2)

fleeTable = NULL
for(i in seq_len(dim(fleeTableLanding)[2])){
  columns = cbind(Desembarque = fleeTableLanding[, i], Esfuerzo = fleeTableEffort[, i])
  fleeTable = cbind(fleeTable, columns)
}

rowNamesTable = rownames(fleeTableLanding)
colNamesTable = colnames(fleeTable)

fleeTable = rbind(fleeTable, apply(fleeTable, 2, sum, na.rm = TRUE))
rownames(fleeTable) = c(rowNamesTable, "Total")

fleeTable = cbind(fleeTable,
                  Desembarque = apply(fleeTable[,seq(from = 1, by = 2, to = dim(fleeTable)[2])], 1, sum, na.rm = TRUE),
                  Esfuerzo = apply(fleeTable[,seq(from = 2, by = 2, to = dim(fleeTable)[2])], 1, sum, na.rm = TRUE))

fleeTable = rbind(colnames(fleeTable), fleeTable)
colnames(fleeTable) = c(gsub("_", " ", rep(colnames(fleeTableLanding), each = 2)), "Total", "Total")

pander::pander(fleeTable, align = "c", split.table = Inf, )
```


# Desembarque y esfuerzo diario
```{r, echo=FALSE, message=FALSE, fig.height=5, fig.width=8}
plot(x, language = "spanish", ploType = "plotJoined", daysToPlot = daysToPlot,
     colBar = "black")
```

# Desembarque y esfuerzo por puerto
```{r, echo=FALSE, message=FALSE}
#Landing
portTableLanding = x$landing$data
portTableLanding = melt(portTableLanding, id.vars= names(portTableLanding[ , c(1:3)]))
portTableLanding = tapply(portTableLanding$value, list(portTableLanding[, 1], portTableLanding[, 4]), sum)

portInfoLanding = getPort(colnames(portTableLanding))
colnames(portTableLanding) = portInfoLanding$data$name
portTableLanding = round(t(portTableLanding[, order(portInfoLanding$data$lat, decreasing = TRUE)]), digits = 2)

#Effort
portTableEffort  = x$effort$data
portTableEffort  = melt(portTableEffort, id.vars= names(portTableEffort[ , c(1:3)]))
portTableEffort  = tapply(portTableEffort$value, list(portTableEffort[, 1], portTableEffort[, 4]), sum)

portInfoEffort = getPort(colnames(portTableEffort))
colnames(portTableEffort) = portInfoEffort$data$name
portTableEffort = round(t(portTableEffort[, order(portInfoEffort$data$lat, decreasing = TRUE)]), digits = 2)

#years
yearsTable = sort(colnames(portTableLanding), decreasing = FALSE)

porTable = NULL
for(i in seq_len(dim(portTableLanding)[2])){
  columns = cbind(Desembarque = portTableLanding[, i], Esfuerzo = portTableEffort[, i])
  porTable = cbind(porTable, columns)
}

porTable = cbind(porTable,
                 Desembarque = apply(porTable[, seq(from = 1, by = 2, to = dim(porTable)[2])], 1, sum, na.rm = TRUE),
                 Esfuerzo = apply(porTable[, seq(from = 2, by = 2, to = dim(porTable)[2])], 1, sum, na.rm = TRUE))

rowNamesTable = rownames(porTable)
colNamesTable = colnames(porTable)

porTable = rbind(porTable, apply(porTable, 2, sum, na.rm = TRUE))
rownames(porTable) = c(rowNamesTable, "Total")

porTable = rbind(colnames(porTable), porTable)
colnames(porTable) = c(rep(yearsTable, each = 2), "Total", "Total")

pander::pander(porTable, align = "c", split.table = Inf)
```

